Restart on-failure
Specifically, celery beat needs it else

django.db.utils.ProgrammingError: (1146, "Table 'chris.django_celery_beat_periodictask' doesn't exist")